version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ReadingIsGoodProject/Dockerfile
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  vue:
    build: ./readingisgoodvue
    ports:
      - "8080:8080"
    volumes:
      - ./readingisgoodvue:/app
      - /app/node_modules
