# Generated by Django 5.0 on 2023-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingIsGoodOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(max_length=110),
        ),
    ]
