# Generated by Django 5.0 on 2023-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingIsGoodBook', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
